// Build tool: turns files, joined in order, into a C source file defining
//     const unsigned char NAME[];  const size_t NAME_len;
// so the compiler can carry the runtime inside itself.
//
//     embed OUTPUT NAME INPUT...

#include <stdio.h>
#include <stdlib.h>

static char *read_all(const char *path, long *size) {
    FILE *f = fopen(path, "rb");
    if (!f || fseek(f, 0, SEEK_END) != 0 || (*size = ftell(f)) < 0 || fseek(f, 0, SEEK_SET) != 0) {
        fprintf(stderr, "embed: can't read %s\n", path);
        exit(1);
    }
    char *data = malloc((size_t)*size + 1);
    if (!data || fread(data, 1, (size_t)*size, f) != (size_t)*size) {
        fprintf(stderr, "embed: can't read %s\n", path);
        exit(1);
    }
    fclose(f);
    return data;
}

int main(int argc, char **argv) {
    if (argc < 4) {
        fprintf(stderr, "usage: embed OUTPUT NAME INPUT...\n");
        return 2;
    }
    FILE *out = fopen(argv[1], "w");
    if (!out) {
        fprintf(stderr, "embed: can't write %s\n", argv[1]);
        return 1;
    }
    fprintf(out, "// Generated by tools/embed.c from");
    for (int f = 3; f < argc; f++) fprintf(out, " %s", argv[f]);
    fprintf(out, ". Do not edit.\n#include <stddef.h>\n\nconst unsigned char %s[] = {", argv[2]);
    long total = 0;
    for (int f = 3; f < argc; f++) {
        long size;
        char *data = read_all(argv[f], &size);
        for (long i = 0; i < size; i++, total++) {
            fprintf(out, "%s%u,", total % 16 == 0 ? "\n    " : " ", (unsigned char)data[i]);
        }
        free(data);
    }
    fprintf(out, "\n    0\n};\nconst size_t %s_len = %ld;\n", argv[2], total);
    if (fclose(out) != 0) {
        fprintf(stderr, "embed: can't write %s\n", argv[1]);
        return 1;
    }
    return 0;
}
